name: Super-Linter
on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]
jobs:
  ci_to_develop:
    name: Lint code base
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    name: Run Super-Linter
      uses: github/super-linter@v3

      with:
      - run: npm ci
      - run: npm test
      - run: npm run build