name: Swift

on:
  push:

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests
    - name: UITest
      - name: testing ... iPhone 12
        run: xcodebuild test-without-building -scheme affirm-me-test -workspace affirm-me.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 12'