name: Feature pipeline
on: push
jobs:
  setup:
    runs-on: macOS-latest
    steps:
      - run: ./setup_server.sh
  build:
    needs: setup
    runs-on: macOS-latest
    steps:
      - run: ./build_server.sh
  test:
    needs: build
    runs-on: macOS-latest
    steps:
      - run: |
      - only-testing: FoodListViewModelTests