name: integracion con node.JS
on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]
jobs:
  ci_to_develop:
    runs-on: macos-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
      - run: npm ci
      - run: npm test
      - run: npm run build