name: Swift

on:
  push:

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: iOS build setup
      run: |
        xcodebuild build-for-testing -scheme WW-Exercise-01-test -workspace WW-Exercise-01.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11' #-allowProvisioningUpdates